version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "4672:5672"
      - "41673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'